src/flux: Remove `$advice_on_option_error`, remove support for backslash escapes from `message()`, add `--error-opt` to `message()`.

diff --git a/src/flux b/src/flux
--- a/src/flux
+++ b/src/flux
@@ -11,17 +11,23 @@ message(){
 	if [[ -n "$timestamps" ]]; then
 		local_timestamp="$(printf "%($timestamp_format)T") "
 	fi
-	# Print message depending by type
+	# Print message depending by passed option
 	case "$1" in
 	--error )
 		shift 1
-		echo -e "$local_timestamp$prefix_error $*" >&2
+		echo "$local_timestamp$prefix_error $*" >&2
 		local_log_prefix="$prefix_error"
+	;;
+	--error-opt )
+		# Setting '$local_log_prefix' is unneeded because this message will not be logged ever
+		shift 1
+		echo "$local_timestamp$prefix_error $*" >&2
+		echo "$prefix_info Try 'flux --help' for more information."
 	;;
 	--info )
 		shift 1
 		if [[ -z "$quiet" ]]; then
-			echo -e "$local_timestamp$prefix_info $*"
+			echo "$local_timestamp$prefix_info $*"
 			local_log_prefix="$prefix_info"
 		else
 			return 0
@@ -30,7 +36,7 @@ message(){
 	--verbose )
 		shift 1
 		if [[ -n "$verbose" ]]; then
-			echo -e "$local_timestamp$prefix_verbose $*"
+			echo "$local_timestamp$prefix_verbose $*"
 			local_log_prefix="$prefix_verbose"
 		else
 			return 0
@@ -38,21 +44,21 @@ message(){
 	;;
 	--warning )
 		shift 1
-		echo -e "$local_timestamp$prefix_warning $*" >&2
+		echo "$local_timestamp$prefix_warning $*" >&2
 		local_log_prefix="$prefix_warning"
 	esac
 	# Print message with timestamp to log file if responding option is specified and logging has been allowed before event reading
 	if [[ -n "$allow_logging" ]]; then
 		# Check log file for read-write access before store message to log
 		if check_rw "$log"; then
-			echo -e "$local_timestamp$local_log_prefix $*" >> "$log"
+			echo "$local_timestamp$local_log_prefix $*" >> "$log"
 		else
 			allow_logging='' message --warning "Unable to write message to log file '$log', recreate it or check read-write access!"
 		fi
 	fi
 	# Print message as notification if '--notifications' option is specified and those have been allowed (before start event reading)
 	if [[ -n "$allow_notifications" ]]; then
-		notify-send "$(echo -e "$*")"
+		notify-send "$(echo "$*")"
 	fi
 }
 
@@ -141,9 +147,6 @@ prefix_warning='[!]'
 
 # Set default timestamp format for logger
 timestamp_format='[%Y-%m-%dT%H:%M:%S%z]'
-
-# Additional text for errors related to option parsing
-advice_on_option_error="\n$prefix_info Try 'flux --help' for more information."
 
 # Load functions from modules
 load_modules
